name: CI

on: [ push, pull_request ]

jobs:
  cached-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: gradle
      - name: Execute
        run: |
          ./gradlew build -x :examples:assets:lib-multiplatform:build
          ./gradlew clean # preserves configuration caches
          ./gradlew build -x :examples:assets:lib-multiplatform:build

  build-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: gradle
      - name: Execute
        run: |
          ./gradlew build -x :examples:assets:lib-multiplatform:build
          ./gradlew build -x :examples:assets:lib-multiplatform:build
