name: CI

on: [ push, pull_request ]

jobs:
  cached-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: gradle
      - name: Calculate Cache
        run: ./gradlew build --dry-run
      - name: Clean Build Cache
        run: ./gradlew clean # preserves configuration caches
      - name: Run Cached Build
        run: ./gradlew build
      - name: Run Cached Build1.5
        run: ./gradlew build
      - name: Clean Build Cache2
        run: ./gradlew clean
      - name: Run Cached Build2
        run: ./gradlew build
